spring:
  application:
    name: APIRestSpringBoot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_rest_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 14062004Evelyn
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false