spring:
  application:
    name: APIRestSpringBoot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_rest_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 14062004Evelyn
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    br.com.evelyniglesiass: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true